# Generated by Django 4.1.2 on 2023-01-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_order_user_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
    ]
