# Generated by Django 4.1.2 on 2022-12-31 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name_plural': 'Cart Items'},
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='itemID',
            new_name='item',
        ),
    ]
