# Generated by Django 4.1.2 on 2022-12-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='bigImage',
            field=models.ImageField(upload_to='static/website/img/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='static/website/img/'),
        ),
    ]
